// Generated by CoffeeScript 1.4.0

/*
*/


(function() {
  var __slice = [].slice;

  this.CallbackInvalidator = (function() {

    function CallbackInvalidator() {
      this.cbs = [];
    }

    CallbackInvalidator.prototype.add = function(cb, scope) {
      var wrapped,
        _this = this;
      if (typeof cb === "function") {
        wrapped = function() {
          var args;
          args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
          if (_this.cbs.indexOf(cb) !== -1) {
            return cb.apply(scope || null, args);
          }
        };
        this.cbs.push(wrapped);
      }
      return wrapped;
    };

    CallbackInvalidator.prototype.reset = function() {
      return this.cbs = [];
    };

    return CallbackInvalidator;

  })();

}).call(this);
